[package]
name = "tuios-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
limine = "0.5"
x86_64 = { version = "0.15", features = ["instructions"] }
uart_16550 = "0.3"
spinning_top = "0.3"
linked_list_allocator = "0.10"
pic8259 = "0.11"
spin = "0.9"
bitflags = "2"
smoltcp = { version = "0.12", default-features = false, features = ["medium-ethernet", "proto-ipv4", "socket-dhcpv4", "socket-icmp", "socket-tcp", "socket-dns", "alloc"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
