timeout: 0
serial: yes
verbose: yes
default_entry: 1

/TuiOS Linux (padrao)
    protocol: linux
    kernel_path: boot():/vmlinuz
    module_path: boot():/initrd

/TuiOS Rust Kernel (experimental)
    protocol: limine
    kernel_path: boot():/kernel
